### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [pmasior/gomoku-with-computer#16]
1. `# -*- coding: utf_8 -*-` nic nie znaczy w Pythonie 3.
2. Czemu `str(" ")` w `develop.py`?
3. Co by Pan powiedział na zmianę `FPS` na `FRAME_RATE_Hz` lub coś podobnego (*vide* punkt o skrótach w 2. rozdziale i punkt o jednostkach miar w 3. rozdziale Poradnika)?
4. W klasie `Gomoku` wolałbym `human_wins` i `computer_wins`.
5. Po `class Gui`, `class Player` itp. niepotrzebne są nawiasy.
6. Wolałbym, żeby Human i Computer byli pisani obaj wielką albo obaj małą literą.
7. Zmienić `"Won Human"` itp. na `"Human won"`.
8. [Tutaj](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/gui.py#L73) brakuje wyrazu `"stones"`.
9. [Co do tego wiersza](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/gui.py#L89) proszę przeczytać punkt o sklejaniu napisów z 2. rozdziału.
10. Porównania z `None` [tutaj](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/player.py#L24), [tutaj](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/tie.py#L46) itp. robimy przez `is` i `is not`, bo to singleton.
11. Co do [tego wiersza](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/player.py#L47), [tego wiersza](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/tie.py#L120) itp. proszę przeczytać punkt o łamaniu wierszy z 2. rozdziału.
11. [Tutaj](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/player.py#L86) jestem ciekaw dalszego ciągu.
12. [Tutaj](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/player.py#L142) dwie uwagi naraz: zamiast `if winner == True:` w dobrym tonie jest pisać `if winner:`; zmienna `winner` ma złą nazwę — czy chodziło o `game_ended` lub coś podobnego?
13. [Tutaj](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/player.py#L235) wolałbym nazwaną trzecią wartość, np. `EMPTY`.
14. [Czcionka](https://github.com/pmasior/gomoku/blob/562eb65f5fba82b111137fdc656446df37cf8d7a/License.txt#L7) wygląda [tak](https://upload.wikimedia.org/wikipedia/commons/a/a1/Letter_2007.jpg). Panu chodzi o font.

**Comment by MarcinCiura** [comment]
3. Wycofuję się z herców. `FRAMES_PER_SECOND` będzie OK.

**Comment by pmasior** [comment]
Dziękuję za zgłoszenie błędów. Rozwiązałem je.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.
1. [Te kolory](https://github.com/pmasior/gomoku/blob/f0e8f669d5c3e1923d1317e1032525eeb95c3c4c/constants.py#L15) ponazywać zgodnie z funkcją, nie z zawartością (2. rozdział).
2. [Pylint by się nie czepiał `i` i `j`](https://github.com/pmasior/gomoku/blob/f0e8f669d5c3e1923d1317e1032525eeb95c3c4c/develop.py#L24). A gdzie indziej zamiast `x` i `y` `xx` i `yy` powinny go zadowolić.
3. [To wyłączenie ostrzeżenia](https://github.com/pmasior/gomoku/blob/f0e8f669d5c3e1923d1317e1032525eeb95c3c4c/gomoku.py#L14) można dać raz, nad `import constants`.
4. [Zmiany czegokolwiek poza danym obiektem](https://github.com/pmasior/gomoku/blob/f0e8f669d5c3e1923d1317e1032525eeb95c3c4c/gui.py#L14) zdecydowanie do `main()` (4. rozdział).
5. [Czy to `self.color`](https://github.com/pmasior/gomoku/blob/f0e8f669d5c3e1923d1317e1032525eeb95c3c4c/stone.py#L16) jest używane gdzie indziej? Jeśli nie, to go nie ustawiać, tylko przekazać `color` do `set_image()`.
6. [Lepsze `import player`](https://github.com/pmasior/gomoku/blob/f0e8f669d5c3e1923d1317e1032525eeb95c3c4c/tie.py#L9) (2. rozdział).
7. Dopisać testy do czegokolwiek (3. rozdział).

**Comment by pmasior** [comment]
Dziękuję za zgłoszenie. Poprawiłem błędy.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość.
1. [Tu](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/gomoku.py#L21) wolałbym coś, co bym zrozumiał.
2. [Czy to 5 i niżej 6](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/player.py#L178) dałoby się zamienić na stałe?
3. [Teraz ma Pan `i` i `j` oraz `move_n` i `move_m`](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/player.py#L73) — nie dość, że inne litery, to jeszcze w innej kolejności.
4. [`for i, j in ...`](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/player.py#L298) (3. rozdział). Nadto słabe jest nadpisywanie `i` i `j` — argumentów metody — przez inne `i` i `j` w jej środku.
5. `test.py` przemianować na `tie_test.py` (3. rozdział).
6. [Temu zaradzi](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/test.py#L15) `r` przed `"""`.
7. `requirements.txt` posortować :>
8. [Z tego](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/test.py#L18) zrobić funkcję — jeśli potrzebną gdzie indziej, to gdzie indziej; jeśli nie, to tylko w module od testów.
9. [Używanie `numpy`](https://github.com/pmasior/gomoku/blob/48b86f5d3a97c558c2e2f24b2eb2051b26d4e1fa/test.py#L119) tylko do takich uproszczeń w testach to przegięcie. Lepsze pętle lub *list comprehensions*.

**Comment by pmasior** [comment]
Szanowny Panie Doktorze,
dziękuję za uwagi do projektu. Poprawiłem błędy

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość.
LGTM. Gratuluję, jest Pan dziewiąty.
W wolnej chwili proszę poprawić poniższe miejsca:

1. [Tu `0,` niepotrzebne](https://github.com/pmasior/gomoku/blob/6ce791d7e96d44230cba7ba720686d8a5ae91b12/player.py#L48).
2. [Co z tym kodem?](https://github.com/pmasior/gomoku/blob/6ce791d7e96d44230cba7ba720686d8a5ae91b12/tie.py#L12) Zamienić na ludzki.

**Comment by pmasior** [comment]
Szanowny Panie Doktorze, 
dziękuję za wiadomość. Poprawiłem kod.
